

export const ADD_TODO = 'ADD_TODO'
export const COMPLETE_TODO = 'COMPLETE_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'
export const ACTIVE_TODO = 'ACTIVE_TODO'
export const INACTIVE_TODO = 'INACTIVE_TODO'
